language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"
# install:
#  - npm install -g mocha istanbul
#  - npm install
# script: "npm run travis"
cache:
  directories:
    - node_modules
